// This file is auto-generated by better-auth. 

import { createAuthClient } from "better-auth/react";
import { nextCookies } from "better-auth/next-js";
import { usernameClient } from "better-auth/client/plugins";
import { serverUrl } from "@/environment";

const betterAuthClient = createAuthClient({
  baseURL: serverUrl,
  plugins: [ usernameClient(),nextCookies()],
});

export default betterAuthClient;