// This file is auto-generated by better-auth. 

import { createAuthClient } from "better-auth/react";
import { nextCookies } from "better-auth/next-js";
import { usernameClient } from "better-auth/client/plugins";

const betterAuthClient = createAuthClient({
  baseURL: "http://localhost:3000",
  plugins: [nextCookies(), usernameClient()],
});

export default betterAuthClient;